from django.urls import path

from App import views, adminviews, customerviews, managerviews

urlpatterns=[
    path('base1',views.base1,name='base1'),
    path('base2',customerviews.base2,name='base2'),
    path('regCustomer',views.regCustomer,name='regCustomer'),
    path('regManager',views.regManager,name='regManager'),
    path('login_view',views.login_view,name='login_view'),
    path('adminPage',adminviews.adminPage,name='adminPage'),
    path('',customerviews.customerPage,name='customerPage'),
    path('managerPage',managerviews.managerPage,name='managerPage'),
    path('ProductAdd',adminviews.ProductAdd,name='ProductAdd'),
    path('ProductView/<int:id>/', adminviews.ProductView, name='ProductView'),
    path('CategoryAdd', adminviews.CategoryAdd, name='CategoryAdd'),
    path('updateProduct/<int:id>/', adminviews.updateProduct, name='updateProduct'),
    path('deleteProduct/<int:id>/', adminviews.deleteProduct, name='deleteProduct'),
    path('notification',adminviews.notification,name='notification'),
    path('noteView',customerviews.noteView,name='noteView'),
    path('cData',adminviews.cData,name='cData'),
    path('mData',adminviews.mData,name='mData'),
    path('cProductView/<int:id>/',customerviews.cProductView,name='cProductView'),
    # path('buy',customerviews.buy,name='buy'),
    path('delivery/<int:id>/',customerviews.delivery,name='delivery'),
    path('addCart/<int:id>/',customerviews.addCart,name='addCart'),
    path('cart',customerviews.cart,name='cart'),
    path('delete/<int:id>/',customerviews.delete,name='delete'),
    path('quantity/<int:id>/', customerviews.quantity, name='quantity'),
    path('remove/<int:id>/', customerviews.remove, name='remove'),
    # path('total', customerviews.total, name='total'),
    path('products', customerviews.products, name='products'),
    path('oneItem/<int:id>/', customerviews.oneItem, name='oneItem'),
    path('rent',managerviews.rent,name='rent'),
    path('rentView',managerviews.rentView,name='rentView'),
    path('deleteRent/<int:id>/',managerviews.deleteRent,name='deleteRent'),
    path('updateRent/<int:id>/',managerviews.updateRent,name='updateRent'),
    path('rentCate',customerviews.rentCate,name='rentCate'),
    path('rentProduct/<int:id>/',customerviews.rentProduct,name='rentProduct'),
    path('oneProduct/<int:id>/',customerviews.oneProduct,name='oneProduct'),
    path('rentalRequest/<int:id>/',customerviews.rentalRequest,name='rentalRequest'),
    path('Renteditem',customerviews.Renteditem,name='Renteditem'),
    path('checkout/<int:id>/',customerviews.checkout,name='checkout'),
    path('quantity1/<int:id>/', customerviews.quantity1, name='quantity1'),
    path('remove1/<int:id>/', customerviews.remove1, name='remove1'),
    path('addDay/<int:id>/', customerviews.addDay, name='addDay'),
    path('removeDay/<int:id>/', customerviews.removeDay, name='removeDay'),
    path('thankyou',customerviews.thankyou,name='thankyou'),
    path('orders',managerviews.orders,name='orders'),
    path('orderDetails',customerviews.orderDetails,name='orderDetails'),
    path('cancelRent/<int:id>/',customerviews.cancelRent,name='cancelRent'),
    path('orderUpdate/<int:id>/',managerviews.orderUpdate,name='orderUpdate'),
    path('review/<int:id>/',customerviews.review,name='review'),
    path('customerProfile',customerviews.customerProfile,name='customerProfile'),
    path('orderDetails2',customerviews.orderDetails2,name='orderDetails2')

]